<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="ParallelPID" Id="{c6bece98-9eca-4ec6-acee-eba02304d025}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM ParallelPID
VAR
	prevError: REAL := 0;
	prevIntegral: REAL := 0;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>